language: generic

sudo: required

env:
  globaL:
    - DOCKER_VERSION=1.12.0-0~trusty
    - DOCKER_COMPOSE_VERSION=1.8.0
    - COMPOSE_HTTP_TIMEOUT=3600

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_install:
  # upgrade docker-engine to specific version
  - sudo ./travis/prepare-docker.sh

  - sudo mkdir vendor
  - sudo chmod 777 vendor

  - sudo mkdir bin
  - sudo chmod 777 bin

script:
  # The test run is included in the docker-entrypoint-tests.sh file.
  - sudo docker-compose run hostmaster --rm
