version: '2'

services:

  hostmaster:
    image: aegir/hostmaster
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    command:
      - run-tests.sh
    environment:
      VIRTUAL_HOST: aegir.local.computer
      MYSQL_ROOT_PASSWORD: strongpassword
      AEGIR_MAKEFILE: /var/aegir/tests/travis/build-hostmaster-local.make
    tty: true
    stdin_open: true
    volumes:
      - ../:/var/aegir/tests
      - /home/travis/build/aegir-project/hostmaster:/source/hostmaster

  database:
    image: mariadb

    # Disable logging for this container, for testing environment.
    logging:
      driver: "none"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword

