version: '2'

services:

  hostmaster:
    image: aegir/hostmaster
    privileged: true
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    command:
      - run-tests.sh
    environment:
      VIRTUAL_HOST: aegir.local.computer
      MYSQL_ROOT_PASSWORD: strongpassword
      AEGIR_MAKEFILE: /usr/share/drush/commands/provision/aegir.make
    tty: true
    stdin_open: true
    volumes:
      - ../:/var/aegir/tests
      - /home/travis/build/aegir-project/provision:/usr/share/drush/commands/provision

  database:
    image: mariadb

    # Disable logging for this container, for testing environment.
    logging:
      driver: "none"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword

    # These options are needed for Drupal 7.50 and up for full UTF-8 support.
    # See https://www.drupal.org/node/2754539
    command: mysqld --innodb-large-prefix --innodb-file-format=barracuda --innodb-file-per-table
