version: '2'

services:

  hostmaster:
    image: aegir/hostmaster
    command:
      - run-tests.sh
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      VIRTUAL_HOST: aegir.local.computer
      MYSQL_ROOT_PASSWORD: strongpassword
    tty: true
    stdin_open: true
    volumes:
      - ../:/var/aegir/tests

  database:
    image: mariadb

    # Disable logging for this container, for testing environment.
    logging:
      driver: "none"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword

