version: '2'

services:

  hostmaster:
    image: aegir/hostmaster:local
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    entrypoint:
    # See https://github.com/aegir-project/dockerfiles/blob/master/docker-entrypoint-tests.sh
      - docker-entrypoint-tests.sh
    environment:
      VIRTUAL_HOST: aegir.local.computer
      MYSQL_ROOT_PASSWORD: strongpassword
      AEGIR_MAKEFILE: /var/aegir/tests/travis/build-hostmaster-local.make
    tty: true
    stdin_open: true
    volumes:
      - ../:/var/aegir/tests
      - /home/travis/build/aegir-project/hostmaster:/var/aegir/hostmaster-source

  database:
    image: mariadb

    # Disable logging for this container, for testing environment.
    logging:
      driver: "none"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword

    # These options are needed for Drupal 7.50 and up for full UTF-8 support.
    # See https://www.drupal.org/node/2754539
    command: mysqld --innodb-large-prefix --innodb-file-format=barracuda --innodb-file-per-table